<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_click</name>
   <tag></tag>
   <elementGuidId>e0c8c9cd-2630-4cc9-8f82-005fea376fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login']/div[5]/p/a/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8188e3f3-22e9-481f-969a-d2bd916ef457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>2cb1f192-5624-40e5-9272-40246caa3d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/div[5]/p[1]/a[1]/b[1]</value>
      <webElementGuid>cf0aa69d-6fb2-49ac-8c2c-18347753f652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div[5]/p/a/b</value>
      <webElementGuid>e1e1dcc8-47a2-41d3-9cde-c5bb6ee769a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::b[1]</value>
      <webElementGuid>4e205f79-61f5-4175-9f90-d1015c47b4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::b[2]</value>
      <webElementGuid>2bc43247-975a-4fb2-9c6c-b59b5f81f99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt; BACK'])[1]/preceding::b[1]</value>
      <webElementGuid>d81e287e-8b35-45ea-841d-0bd5fbb99180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'login', '&quot;', ')/div[5]/p[1]/a[1]/b[1]')])[1]/preceding::b[1]</value>
      <webElementGuid>f42d7d52-e3ec-46c8-bab2-a05169ca9f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='click']/parent::*</value>
      <webElementGuid>c87642cb-02ab-4adc-b34a-28bb3002eacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p/a/b</value>
      <webElementGuid>a09ffe67-e4af-4872-afd1-c1e4bff85d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'click' or . = 'click')]</value>
      <webElementGuid>c2c60848-23ac-4bf4-8b3e-d0fb24e13b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
