<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Register_ConfirmPassword</name>
   <tag></tag>
   <elementGuidId>0584d5ff-ba13-48cc-b054-07ac91455638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c5f79f2-2929-4667-a017-01f36d687b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b1460dd8-e690-44cc-b4eb-2b09201697a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__field</value>
      <webElementGuid>5c933b6c-7f21-4453-a07f-4a33d452e3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>8e40be88-9896-4b18-a85f-66a2ef261df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userConfirmPass</value>
      <webElementGuid>3484fe6c-e67c-44e2-9069-d68c864c9e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfpassword</value>
      <webElementGuid>6bb0cecc-ec3a-4508-a859-a160b92a91ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfpassword&quot;)</value>
      <webElementGuid>b3ce9775-9c85-4ada-8259-be4913e41523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfpassword']</value>
      <webElementGuid>d1deda61-eaf0-45c4-a552-90dd823dee33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='category']/div/div/div/div/form/div[7]/input</value>
      <webElementGuid>a1327325-c204-4b66-8936-fed849458180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>f3084a2b-f448-4c07-9dff-a0f74bfeeacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Confirm Password' and @name = 'userConfirmPass' and @id = 'cfpassword']</value>
      <webElementGuid>a2f0dcbf-3534-416b-9e58-0860839333bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
