<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_userAddress</name>
   <tag></tag>
   <elementGuidId>420574c7-f6dd-4cc9-abb8-bbd5369a48a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d51e8f59-1787-4fa3-b69d-5d92e537e980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>779aec38-a6a4-4ed5-ba29-67f621a486e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__field</value>
      <webElementGuid>29a16cf4-4379-404e-9ba7-818fdd2b4363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>8b1936f8-914c-4553-81da-ac1bc5a57980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userAddress</value>
      <webElementGuid>515fe0eb-66ce-40d5-b620-af2fbcda4131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>65adbaba-5899-4ef9-8250-edbc825dcabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address&quot;)</value>
      <webElementGuid>b7de35a1-fef3-4c5d-b625-56e5a69ee33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address']</value>
      <webElementGuid>00d4657b-a369-44cf-9b2e-029e64260ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='category']/div/div/div/div/form/div[4]/input</value>
      <webElementGuid>3d1c283c-21ac-4f87-affa-4804b782da54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>420cebd7-7a38-487c-8751-de0d115eaa6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'address' and @placeholder = 'address' and @name = 'userAddress' and @id = 'Address']</value>
      <webElementGuid>4ef90df3-c076-4202-bc3a-855f81443a9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
