<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Register_Lastname</name>
   <tag></tag>
   <elementGuidId>bef256cf-13d9-4d6a-8fb9-4c3e0f7c35d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Lastname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c7e147d-9616-47be-b50f-14fbcc40fb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b7e4573-8201-426d-a316-fd7e03a0833f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__field</value>
      <webElementGuid>c9312d77-e309-490f-af38-f7fa7674223f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lastname</value>
      <webElementGuid>8a3b8a44-2ff0-4126-84ad-7c24d4118ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lastname</value>
      <webElementGuid>9c9192e8-683c-47cb-be79-62fafea83f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Lastname</value>
      <webElementGuid>eb1e852c-9336-4909-94eb-a3f157507156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Lastname&quot;)</value>
      <webElementGuid>bd34129c-c6f5-4dd3-acdc-ac349664571b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Lastname']</value>
      <webElementGuid>5143bbf6-d345-4bda-bf5b-fb454c5bbf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='category']/div/div/div/div/form/div[2]/input</value>
      <webElementGuid>15bba844-d3fb-462d-9e1a-cda71f2b360d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>33bdd8b6-603f-4e59-abe1-9624baea890d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = 'Lastname' and @name = 'Lastname' and @id = 'Lastname']</value>
      <webElementGuid>eef826b9-a214-45de-902b-403b8cfba0b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
