<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Lastname</name>
   <tag></tag>
   <elementGuidId>c24b18e5-be34-4c69-96ab-e74efec39ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='category']/div/div/div/div/form/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>50932721-c1c7-49b9-9ad5-d40245288f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Lastname</value>
      <webElementGuid>d956dd12-c566-4486-920e-724d3389252d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__label</value>
      <webElementGuid>3a2a3cfa-f258-4d17-9c49-a2866eda1be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lastname</value>
      <webElementGuid>7c127ad1-6208-4e02-8aa5-b0646a2c2f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;bg-transparent&quot;]/form[1]/div[@class=&quot;form__group field&quot;]/label[@class=&quot;form__label&quot;]</value>
      <webElementGuid>25f861a9-86bc-42ff-9908-0b56868b9fbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='category']/div/div/div/div/form/div[2]/label</value>
      <webElementGuid>70a193d6-2d1f-487a-80db-168990437a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::label[1]</value>
      <webElementGuid>2173d090-5511-4634-92f3-0caf80585a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::label[2]</value>
      <webElementGuid>0027b8f3-e40e-40e3-81c5-d0c60fdc8c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::label[1]</value>
      <webElementGuid>03f31f57-9684-4753-8ee8-7b18787ab773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::label[2]</value>
      <webElementGuid>b46356bc-8d30-4ad6-84d3-c0911dbf120e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lastname']/parent::*</value>
      <webElementGuid>b391fe9e-986f-407d-ba2d-03ee411a269d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>3172680c-c191-4904-86d8-efe747dcd113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Lastname' or . = 'Lastname')]</value>
      <webElementGuid>b9c7dcfc-fb6f-44e1-bdfe-448f108bc1b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
